### CREAR UN NUEVO USUARIO ###
POST http://localhost:3000/api/user
Content-Type: application/json

{
  "nombre": "Chanchito Feliz",
  "correo": "chanchito@gmail.com",
  "contraseña": "supersecreta",
  "esSocio": true,
  "direcciones": [
    {
      "calle": "Av. Central 123",
      "ciudad": "Santiago",
      "region": "RM",
      "codigoPostal": "1234567"
    }
  ]
}

### LISTAR USUARIOS

GET http://localhost:3000/api/user

### Borrar un USUARIO por ID

DELETE http://localhost:3000/api/user/

### Activar un USUARIO por ID

PATCH http://localhost:3000/api/user/<ID>/activate

### Desactivar un USUARIO por ID

PATCH http://localhost:3000/api/user/<ID>/deactivate